# Generated by Django 4.2 on 2023-04-24 08:03

from django.db import migrations, models
import django.db.models.deletion
import yamlfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DockerComposeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=255, unique=True)),
                ('docker_compose_template', yamlfield.fields.YAMLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NginxTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bitbucket_slug', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('cd_name', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(default='api', max_length=255)),
                ('image_name', models.CharField(max_length=255, null=True)),
                ('nginx_port', models.IntegerField(blank=True, default=80, null=True)),
                ('service_port', models.IntegerField(blank=True, default=8080, null=True)),
                ('scheduler_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(blank=True, default=False)),
                ('deploy_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdtool.dockercomposetemplate')),
                ('nginx_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdtool.nginxtemplate')),
            ],
        ),
    ]
